name: test_app
command_prefix: "~"
commands: 
  ls:
    function: os.listdir
  reg:
    function: discordify.commands.register_sync_func
  print:
    function: print
channel-commands:
  command1:
    function: test_app.to_gray
    channel: bot-spam